import Head from "next/head";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Header from "@/components/Header";
import { Body } from "@/components/Body";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { getProductsCount } from "@/services/handleProducts";

const theme = createTheme({
  palette: {
    primary: { main: "#00539f" },
  },
});

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const counts: number | undefined = await getProductsCount();
    return { props: { counts: counts ?? 0 } };
  } catch (error) {
    console.error("Error fetching product counts:", error);
    return { props: { counts: 0, error: "Failed to fetch product counts" } };
  }
};

export default function Home({
  counts,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Rotech Custom App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/SR_Favicon.png" />
      </Head>
      <main>
        <ThemeProvider theme={theme}>
          <Header />
          <Body productCounts={counts} />
        </ThemeProvider>
      </main>
    </>
  );
}
